os:            osx
osx_image:     xcode9.2
language:      objective-c
xcode_project: EasyRoot.xcodeproj

before_install:
  - pod repo update
  - bundle install
  - pod install

script:
  set -o pipefail && xcodebuild -workspace EasyRoot.xcworkspace -scheme EasyRoot \test | bundle exec xcpretty --color --test
