os:            osx
osx_image:     xcode9.2
language:      objective-c
xcode_project: EasyRoot.xcodeproj

before_install:
  - pod repo update
  - bundle install
  - pod install

script: bundle exec fastlane scan -s EasyRoot

before_script: swiftlint
