os:            osx
osx_image:     xcode9.2
language:      objective-c
xcode_project: EasyRoot.xcodeproj

before_install:
  - bundle install
  - pod install

script:
  set -o pipefail && xcodebuild -project EasyRoot.xcodeproj -scheme EasyRoot \test | bundle exec xcpretty --color --test
